name: iOS

on: [pull_request]

jobs:
  test:
    timeout-minutes: 6
    runs-on: macOS-latest

    steps:
    - name: Swift version
      run: swift --version
    
    - uses: actions/checkout@v4
    
    - name: What schemes?
      run: xcodebuild build test -list
    
    - name: Run iOS tests
      run: |
        xcodebuild test \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          -scheme RectangleTools
