name: watchOS

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
            
    - name: Swift version
      run: swift --version
    
    - name: Run watchOS tests
      run: |
        xcodebuild test \
          -sdk watchsimulator \
          -destination 'platform=watchOS Simulator,name=Any watchOS Simulator Device' \
          -scheme RectangleTools
