name: watchOS

on: [pull_request]

jobs:
  build:

    timeout-minutes: 4
    runs-on: macOS-latest

    steps:
    - name: Set up Swift 6
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '6.0'
    
    - name: Swift version
      run: swift --version
      
    - uses: actions/checkout@v3
    
    - name: Build
      run: swift build
    
    - name: What schemes?
      run: xcodebuild build test -list
    
    - name: Run watchOS tests
      run: xcodebuild build test -destination 'name=Apple Watch Ultra 2 (49mm)' -scheme 'RectangleTools'

