name: watchOS

on: [pull_request]

jobs:
  test:
    timeout-minutes: 4
    runs-on: macOS-latest

    steps:
    - name: Swift version
      run: swift --version
      
    - uses: actions/checkout@v4
    
    - name: What schemes?
      run: xcodebuild build test -list
    
    - name: Run watchOS tests
      run: |
        xcodebuild test \
          -sdk watchsimulator \
          -destination 'platform=watchOS Simulator,name=Apple Watch Ultra 3 (49mm)' \
          -scheme RectangleTools
